### ISSUE TITLE
Jupyter magics

### ISSUE THREAD

**Issue by abingham** [chmp/ipytest#1]
Thanks for your work on this! I've been using `ipytest` for a presentation I'm working on, and it's great. I've put together a jupyter magic that lets me use it more naturally. You can [see it here](https://github.com/abingham/python-testing-presentation/blob/master/pytest_magics.py). 

For the most part, `ipytest` seems to work well. One issue I've found is that `ipytest.clean_tests()` doesn't always seem to work. In particular, if I re-run cells with my magic in jupyter, pytest says it's running more tests than the cell contains (i.e. test functions from other cells, the contents of which should have been cleaned). You can see this by running [this notebook](https://github.com/abingham/python-testing-presentation/blob/master/pytest.ipynb) and running the code cells twice. (Note that you'll need the magics from that repo and `ipytest` along with the notebook.) The real problem may lie with what I'm doing in the magic function, but I'm not sure right now.

Anyhow, what I really want to do is start a discussion with you about `ipytest` and magics in general. Are you interested in integrating magics into `ipytest`? If so, what are your thoughts on how they should work? And even if not, so you have any sense of why `ipytest` is displaying the behavior I'm seeing?

**Comment by chmp** [comment]
Thanks for the comments and for the idea of adding magics :) I chose a different design, when implementing it a week ago ([my implementation](https://github.com/chmp/ipytest/blob/master/ipytest/magics.py), [usage](https://github.com/chmp/ipytest/blob/master/example/Magics.ipynb)). Our designs mainly differ in that I would prefer to keep all the state tied to the `__main__` module. For me it seems easier to debug, since it is directly inspectable using standard python techniques.

Regarding your problem. I only had a quick look over your magic. I would recommend passing the namespace dict as the `items` argument. If you call `clean_tests` without the `items` argument, it will inspect the stack and extract the globals at the call site of `clean_tests`. Since I do not exactly now how `%run` is implemented, I cannot tell you what dict is used In your case. Therefore, I would call `clean_tests` in your case as `clean_tests('test_*', items=sys.modules['__main__'].__dict__)`. 

However, from the way you code works, I would not expect this issue to be the problem, since the test code is not executed inside the `__main__` module. Could it be that your `cells` variable is collecting state?

**Comment by chmp** [comment]
Btw.

**Comment by chmp** [comment]
Probably, you will also re-execute cells and rename tests (in case of typos, for example), won't you? I fear this will be tricky to do, since there is no way to know which tests were renamed. Currently, I just remove all tests and re-execute all testing code. However, this procedure does not seem very manageable for a presentation.

Maybe, the way forward would be to modify your magics: add a unique identifier to each magic line and then use an OrderedDict instead of a list for your cells variable. This way if you re-execute a cell it will overwrite its previous contents. Something along the lines of:

```
# cell 1
%add_tests 1
...

# cell 2
%add_tests 2
...

# cell 3
%run_tests
```

**Comment by abingham** [comment]
Actually, clearing all existing tests before execution of new code is exactly what I have in mind. It's a simple model, and it fits all of my current needs. It's possible that I'll need to account for typos and renamings, but I think I can handle those by re-running all of the necessary cells.

With that said, I'm pretty focussed on my particular needs. If you think a more general, complex model is necessary, then I'm happy to work with that.
