### ISSUE TITLE
How to run doctest with cell magic command?

### ISSUE THREAD

**Issue by tamuhey** [chmp/ipytest#24]
Hi, thanks for this great project!

I want to run doctest with cell magic, as follows:

```
%%run_pytest --doctest-modules
def foo(x):
    """
    >>> foo(2)
    4
    """
    return x*2
```

However, the output says  no tests found:
```
============================= test session starts ==============================
platform darwin -- Python 3.6.9, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/yohei_tamura/work/men
collected 0 items

========================= no tests ran in 0.02 seconds =========================
```

**Comment by chmp** [comment]
Thanks for the feedback and brining this issue up. First, you're right atm I can't think of way to run doctests  with pytest and ipytest. I had a quick look into how that part of the code is implemented and fixing it does not seem to be easy. 

Maybe as a short-time solution, the non-pytest way to execute doc tests should work:

```python
import doctest
doctest.testmod()
```

**Comment by chmp** [comment]
Documenting the "solution" for myself, while pondering, whether this hack is a good idea:

```python
def _run_impl(*args, module, filename, plugins, return_exit_code):
    ...

    with _valid_filename(filename, module) as valid_filename:
        import sys, pathlib
        p = pathlib.Path(valid_filename)
        sys.modules[p.stem] = module
        module.__file__ = str(p.with_suffix(".py"))
        
        ...
```

The reason this works: 

- the collect_file hook of the doctest modules looks for python files (see [here](https://github.com/pytest-dev/pytest/blob/54b6fe2ece715369f4caebadbd0e135335271275/src/_pytest/doctest.py#L111])
- it will import the file (hence the entry in sys.modules) and further it will compare the `__file__` attribute of the imported module with the filename

Remarks:

- this hack is probably only a good idea with temporary files, otherwise this could wreak havoc with the module system
- ipytest should clean up after itself and remove any modifications to the module cache.

**Comment by chmp** [comment]
I added a new config option `register_module` if set to `True` doctests will work as expected:

```python
import ipytest
ipytest.autoconfig(register_module=True)

%%run_pytest --doctest-modules
def foo(x):
    """
    >>> foo(2)
    4
    """
    return x*2
```
